stg 環境をデプロイ (#12)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -89,6 +89,25 @@ jobs:
             pip install awscli==1.18.46
       - yarn_install
       - run:
+          name: create dotenv
+          command: |
+            case << parameters.stage >> in
+              dev)
+                API_ORIGIN=https://dev.api.nojov.kou-pg.com
+              ;;
+              stg)
+                API_ORIGIN=https://stg.api.nojov.kou-pg.com
+              ;;
+              prod)
+                API_ORIGIN=https://api.nojov.kou-pg.com
+              ;;
+              *)
+                echo 'invalid stage!: << parameters.stage >>'
+                exit 1
+            esac
+
+            echo "REACT_APP_API_ORIGIN=${API_ORIGIN}" > .env
+      - run:
           name: build
           command: yarn run build
       - run:
@@ -106,6 +125,9 @@ jobs:
       - setup_aws_credentials
       - terraform:
           stage: dev
+          command: plan
+      - terraform:
+          stage: stg
           command: plan
       - slack/status
 
@@ -157,3 +179,44 @@ workflows:
           stage: dev
           requires:
             - tf_apply_dev
+
+      - slack/approval-notification:
+          requires:
+            - deploy_dev
+          filters:
+            branches:
+              only:
+                - develop
+
+      - approval_deploy:
+          type: approval
+          requires:
+            - deploy_dev
+          filters:
+            branches:
+              only:
+                - develop
+
+      #
+      # stg
+      #
+
+      - tf_apply:
+          name: tf_apply_stg
+          stage: stg
+          requires:
+            - approval_deploy
+          filters:
+            branches:
+              only:
+                - develop
+
+      - deploy:
+          name: deploy_stg
+          stage: stg
+          requires:
+            - tf_apply_stg
+          filters:
+            branches:
+              only:
+                - develop
